kind: project
metadata:
  created: '2025-07-08T18:28:26.407000'
  name: zzz-xingsheng
status:
  state: online
spec:
  conda: ''
  owner: xingsheng
  build:
    source_code_target_dir: /home/mlrun_code/
    image: .demo-call-center-kfp
    commands:
    - pip install SQLAlchemy==2.0.31 &&           echo "" > /empty/requirements.txt
      &&           ls -l /empty/ &&           cat /empty/Dockerfile &&           ls
      -l /home/ &&           rm -rf /home/mlrun-code/project_setup.py
    base_image: mlrun/mlrun-kfp
  workflows:
  - name: calls-generation
    image: .demo-call-center-kfp
    path: ./src/workflows/calls_generation.py
  - name: calls-analysis
    image: .demo-call-center-kfp
    path: ./src/workflows/calls_analysis.py
  params:
    build_image: false
    source: git://github.com/xsqian/demo-call-center.git#main
    gpus: 0
    use_sqlite: false
    default_image_name: .mlrun-project-image-zzz-xingsheng
    default_image: .mlrun-project-image-zzz-xingsheng
  source: git://github.com/xsqian/demo-call-center.git#main
  desired_state: online
  default_image: .mlrun-project-image-zzz-xingsheng
  functions:
  - url: hub://structured_data_generator
    name: structured-data-generator
    kind: job
  - url: ./src/calls_generation/conversations_generator.py
    name: conversations-generator
    kind: job
    with_repo: true
  - url: hub://text_to_audio_generator
    name: text-to-audio-generator
    kind: job
  - url: ./src/calls_analysis/db_management.py
    name: db-management
    kind: job
    with_repo: true
  - url: hub://silero_vad
    name: silero-vad
    kind: job
  - url: hub://transcribe
    name: transcription
    kind: job
  - url: hub://pii_recognizer
    name: pii-recognition
    kind: job
  - url: hub://question_answering
    name: question-answering
    kind: job
  - url: ./src/calls_analysis/postprocessing.py
    name: postprocessing
    kind: job
  - name: call-center-ui
    kind: application
    requirements:
    - vizro==0.1.38
    - gunicorn
  origin_url: git://github.com/xsqian/demo-call-center.git#refs/heads/main
  load_source_on_run: false
